sudo: required
dist: trusty
language: generic
compiler:
  - gcc
env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
  matrix:
    - CI_ROS_DISTRO="indigo"

branches:
  only:
    - master
    - develop
notifications:
  email: false


install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-catkin-tools
  - sudo rosdep init
  - rosdep update
  - rosdep install --from-paths ./ -i -y --rosdistro $CI_ROS_DISTRO
  - sudo apt-get install build-essential
  - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - cd
  - wget https://github.com/PointCloudLibrary/pcl/archive/pcl-1.7.2.tar.gz
  - tar -xvzf pcl-1.7.2.tar.gz
  - cd ~/pcl-pcl-1.7.2
  - mkdir build
  - cd build
  - cmake .. -DBUILD_surface=ON -DBUILD_surface_on_nurbs=ON
  - sudo make install
#  - sudo apt-get remove ros-indigo-pcl-ros ros-indigo-pcl-conversions
  - sudo apt-get remove ros-indigo-perception-pcl ros-indigo-pointcloud-to-laserscan ros-indigo-pcl-ros ros-indigo-pcl-conversions
  - cd
# - source /opt/ros/$CI_ROS_DISTRO/setup.bash
  - mkdir -p $CATKIN_WS_SRC
  - cd $CATKIN_WS_SRC
  - git clone -b indigo-devel https://github.com/ros-perception/pcl_conversions.git
  - git clone -b indigo-devel https://github.com/ros-perception/perception_pcl.git
#  - sudo apt-get install ros-indigo-pcl-ros
#  - sudo apt-get install ros-indigo-pcl-conversions
  - sudo apt-get install ros-indigo-tf2-sensor-msgs
  - sudo apt-get install python-rospkg
  - cd
 

script:
#  - cd
#  - git clone https://github.com/opencv/opencv.git
#  - cd ~/opencv
#  - mkdir build
#  - cd build
#  - cmake ..
#  - make -j7
#  - sudo make install
#  - cd
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
#  - mkdir -p $CATKIN_WS_SRC
  - ln -s $TRAVIS_BUILD_DIR $CATKIN_WS_SRC
  - cd $CATKIN_WS_SRC
  - catkin_init_workspace
  - pip install catkin-pkg
  - pip install empy
#  - sudo apt-get install python-rospkg
  - which python
  - python -V
  - echo $PYTHONPATH
  - dpkg -L python-catkin-pkg
  - cd $CATKIN_WS
  - catkin_make
  - catkin_make install
