set(_CATKIN_CURRENT_PACKAGE "segmenter_jordlee")
set(segmenter_jordlee_VERSION "1.1.0")
set(segmenter_jordlee_MAINTAINER "Unghee Jordan Lee <unghee@umich.edu>")
set(segmenter_jordlee_PACKAGE_FORMAT "1")
set(segmenter_jordlee_BUILD_DEPENDS "eigen_conversions" "geometry_msgs" "liblapack-dev" "message_generation" "roscpp" "pcl_ros" "pcl_conversions" "std_msgs" "tf" "tf_conversions" "visualization_msgs" "cmake_modules" "rail_manipulation_msgs" "cv_bridge" "std_srvs")
set(segmenter_jordlee_BUILD_EXPORT_DEPENDS "eigen_conversions" "geometry_msgs" "liblapack-dev" "message_runtime" "roscpp" "pcl_ros" "pcl_conversions" "std_msgs" "tf" "tf_conversions" "visualization_msgs" "cmake_modules" "rail_manipulation_msgs" "cv_bridge" "std_srvs")
set(segmenter_jordlee_BUILDTOOL_DEPENDS "catkin")
set(segmenter_jordlee_BUILDTOOL_EXPORT_DEPENDS )
set(segmenter_jordlee_EXEC_DEPENDS "eigen_conversions" "geometry_msgs" "liblapack-dev" "message_runtime" "roscpp" "pcl_ros" "pcl_conversions" "std_msgs" "tf" "tf_conversions" "visualization_msgs" "cmake_modules" "rail_manipulation_msgs" "cv_bridge" "std_srvs")
set(segmenter_jordlee_RUN_DEPENDS "eigen_conversions" "geometry_msgs" "liblapack-dev" "message_runtime" "roscpp" "pcl_ros" "pcl_conversions" "std_msgs" "tf" "tf_conversions" "visualization_msgs" "cmake_modules" "rail_manipulation_msgs" "cv_bridge" "std_srvs")
set(segmenter_jordlee_TEST_DEPENDS )
set(segmenter_jordlee_DOC_DEPENDS )
set(segmenter_jordlee_DEPRECATED "")