// Generated by gencpp from file segmenter_jordlee/SegmentObject.msg
// DO NOT EDIT!


#ifndef SEGMENTER_JORDLEE_MESSAGE_SEGMENTOBJECT_H
#define SEGMENTER_JORDLEE_MESSAGE_SEGMENTOBJECT_H

#include <ros/service_traits.h>


#include <segmenter_jordlee/SegmentObjectRequest.h>
#include <segmenter_jordlee/SegmentObjectResponse.h>


namespace segmenter_jordlee
{

struct SegmentObject
{

typedef SegmentObjectRequest Request;
typedef SegmentObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SegmentObject
} // namespace segmenter_jordlee


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::segmenter_jordlee::SegmentObject > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::segmenter_jordlee::SegmentObject&) { return value(); }
};

template<>
struct DataType< ::segmenter_jordlee::SegmentObject > {
  static const char* value()
  {
    return "segmenter_jordlee/SegmentObject";
  }

  static const char* value(const ::segmenter_jordlee::SegmentObject&) { return value(); }
};


// service_traits::MD5Sum< ::segmenter_jordlee::SegmentObjectRequest> should match 
// service_traits::MD5Sum< ::segmenter_jordlee::SegmentObject > 
template<>
struct MD5Sum< ::segmenter_jordlee::SegmentObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::segmenter_jordlee::SegmentObject >::value();
  }
  static const char* value(const ::segmenter_jordlee::SegmentObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::segmenter_jordlee::SegmentObjectRequest> should match 
// service_traits::DataType< ::segmenter_jordlee::SegmentObject > 
template<>
struct DataType< ::segmenter_jordlee::SegmentObjectRequest>
{
  static const char* value()
  {
    return DataType< ::segmenter_jordlee::SegmentObject >::value();
  }
  static const char* value(const ::segmenter_jordlee::SegmentObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::segmenter_jordlee::SegmentObjectResponse> should match 
// service_traits::MD5Sum< ::segmenter_jordlee::SegmentObject > 
template<>
struct MD5Sum< ::segmenter_jordlee::SegmentObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::segmenter_jordlee::SegmentObject >::value();
  }
  static const char* value(const ::segmenter_jordlee::SegmentObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::segmenter_jordlee::SegmentObjectResponse> should match 
// service_traits::DataType< ::segmenter_jordlee::SegmentObject > 
template<>
struct DataType< ::segmenter_jordlee::SegmentObjectResponse>
{
  static const char* value()
  {
    return DataType< ::segmenter_jordlee::SegmentObject >::value();
  }
  static const char* value(const ::segmenter_jordlee::SegmentObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEGMENTER_JORDLEE_MESSAGE_SEGMENTOBJECT_H
